version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  e2e-windows:
    executor: win/default
    steps:
      - checkout
      - run: dotnet tool install --global PowerShell
      - run: node --version
      - run: nvm install lts
      - run: bash TEST=e2e_windows ./scripts/ci.sh
workflows:
  version: 2
  build:
    jobs:
      - e2e-windows
