version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  e2e-windows:
    executor: win/default
    steps:
      - checkout
      - run: dotnet tool install --global PowerShell
      - run: node --version
      - run: nvm install 12.16.0
      - run: nvm use 12.16.0
      - run: bash ./scripts/e2e.npm.publish.sh && ./scripts/e2e.windows.sh
workflows:
  version: 2
  build:
    jobs:
      - e2e-windows
